재고량 감소 비동기 데이터 정합성 보장
Liberty52/product pull request #276
Opened 2023-10-09 13:23 UTC by hseungho

## 스프린트 넘버  : 3
## 메이저 마일스톤 : 상품
### 마이너 마일스톤 : 주문
### 백로그 이름 : 재고량 감소 비동기 데이터 정합성 보장

***
### 작업

1. 단건 주문, 장바구니 복수건 주문 등에서 발생하는 재고량 감소 시 데이터 접근에 대해 Redisson으로 락을 설정
2. 카드결제 주문 실패(위조 결제 등) 시 재고량을 롤백시키기 위한 이벤트 발행 및 컨슘 서비스 추가

각 옵션 디테일 별로 재고량을 확인하여 더티 커밋 등의 문제를 해결하기 위해  
옵션 디테일의 재고를 관리하기 위한 `OptionDetailStockManageService`를 생성하여  
해당 서비스 클래스 안에서 `@DistributedLock`을 이용하여 분산락을 구현하였습니다.

분산락과 관련된 기능들은 `global.annotation.DistributedLock`과 `global.aspect.DistributedLockAspect`에 구현하였습니다.

***
### 테스트 결과
<img width="400" alt="image" src="https://github.com/Liberty52/product/assets/42243302/97efdb2f-9f60-4d86-975b-1db177ee79fc">

<img width="500" alt="image" src="https://github.com/Liberty52/product/assets/42243302/f7348488-b031-4ff8-9272-a266074c146a">

***
### 이슈
@jinlee0 
> `Result<T>` 클래스와 관련하여 `runCatching()` 시 발생된 RuntimeException을 그대로  발생시키기 위해 `getOrThrows()` 인터페이스를 추가하였고, `Failure<T>` 클래스의 `runtimeException` 프로퍼티 추가 및 생성자에서 인자로 받은 `Throwable`을 RuntimeException으로 캐스팅하여 설정하도록 하였습니다.
임의로 추가해보았는데 컨펌 부탁드릴게요. :) 

@ImKunYoung 
> Redis의 설정을 모두 클라우드 환경의 레디스로 물리게끔 하고자 합니다. 로컬 프로파일에도 설정을 추가하면 모든 개발자들의 로컬에도 레디스가 운영되어 있어야 하는 문제가 예상되어서 이처럼 하고자 하는데, 의견 주시면 감사하겠습니다.

2023-10-09 13:57 UTC, jinlee0 requested changes

2023-10-09 13:57 UTC, jinlee0 commented on src/main/java/com/liberty52/product/global/util/Result.java
>          }
`Throwable`을 `RuntimeException`으로 다운캐스팅 할 때 캐스팅 에러가 발생할 수 있을 거 같아요.
그냥 `RuntimeException`만 필드로 가지고 생성자로 RuntimeException을 받아서 초기화하는 게 나아 보입니다.

```suggestion
    public static final class Failure<T> extends Result<T> {
        private final RuntimeException runtimeException;

        public Failure(RuntimException runtimeException ) {
            this.runtimeException = runtimeException;
        }
```
kotlin에선 try catch가 없어서 Thrawable로 해도 되는데 java에선 Throwable이면 무조건 캐치 해야 한다는 걸 깜빡했네요.

nit. `getOrThrow` 없애고 `getOrThrows`를 `getOrThrow`로 메서드 이름 바꾸면 될 듯 해요

2023-10-09 14:02 UTC, hseungho commented on src/main/java/com/liberty52/product/global/util/Result.java
>          }
@jinlee0 
그럼 혹시 RuntimeException이 아닌 Exception의 경우에는 대응되지 못할 수도 있으니, 이런 방향은 어떤가요?

```java
        private final RuntimeException error;

        public Failure(Throwable throwable) {
            if (throwable instanceof RuntimeException e) {
                this.error = e;
            } else {
                this.error = new RuntimeException(throwable);
            }
        }
```

2023-10-10 00:57 UTC, jinlee0 commented on src/main/java/com/liberty52/product/global/util/Result.java
>          }
LGTM

2023-10-10 01:09 UTC, jinlee0 commented on src/main/java/com/liberty52/product/service/applicationservice/impl/OptionDetailMultipleStockManageServiceImpl.java
> +    }
optionDetailIds가 5개 있고 전부 재고량이 1이라고 할 때 (재고량 = [1, 1, 1, 1, 1]), 
그 중 0, 1, 2 번째에 대해 decrement가 성공하고 3 번째에 실패해서 getOrThrow에 의해 try-catch에 잡혀서 롤백(increment) 될 때 모든 optionDetailIds가 increment 되어서 결국
[1, 1, 1, 1, 1] -> [1, 1, 1, 2, 2]이 되는 거 아닌가요??

2023-10-10 01:25 UTC, jinlee0 reviewed
질문

2023-10-10 01:25 UTC, jinlee0 commented on src/main/java/com/liberty52/product/service/applicationservice/impl/OptionDetailStockManageServiceImpl.java
> +    }
요약.
상위 트랜잭션 안에서만 실행된다고 가정했을 때, `@Transactional` 없애고 호출부에서 getOrThrow() 하면 되지 않을까요?

`@Transactional(propagation=Propagation.REQUIRED)`이 되어 있는 걸로 보아 이 함수 안에서 새로운 트랜잭션이 열리고 닫히는 경우를 상정한 거 같은데,
그런 경우에 runCatching으로 감싸버리면 트랜잭션 롤백이 절대 안 되고 트랜잭션이 닫히지 않나요?

만약 단독으로 트랜잭션을 열면 안 되는 경우라면 Propagation.MANDATORY로 하는 게 나을 거 같기도 하구요.

2023-10-10 12:33 UTC, hseungho commented on src/main/java/com/liberty52/product/service/applicationservice/impl/OptionDetailMultipleStockManageServiceImpl.java
> +    }
@jinlee0 
AS-IS
```java
    @Override
    @Transactional(propagation = Propagation.REQUIRED)
    public Result<List<OptionDetail>> decrement(List<String> optionDetailIds, int quantity) {
        return Result.runCatching(() -> {
            try {
                return optionDetailIds.stream()
                        .map(it -> stockManageService.decrement(it, quantity).getOrThrow())
                        .toList();
            } catch (Exception e) {
                // <-- optionDetailids를 루프돌기 때문에 상기 문제가 발생.
                optionDetailIds.forEach(it -> stockManageService.rollback(it, quantity).getOrThrow()); 
                throw e;
            }
        });
    }
```

```java
    @Override
    @Transactional(propagation = Propagation.REQUIRED)
    public Result<List<OptionDetail>> decrement(List<String> optionDetailIds, int quantity) {
        return Result.runCatching(() -> {
           // 롤백을 위한 리스트 선언
            List<OptionDetail> rollbackList = new ArrayList<>();
            try {
                return optionDetailIds.stream()
                        .map(it -> {
                            var optionDetail = stockManageService.decrement(it, quantity).getOrThrow();
                            // 문제 없이 재고량 감소된 옵션을 롤백 리스트에 추가
                            rollbackList.add(optionDetail);
                            return optionDetail;
                        })
                       // 만일 아무 문제 없다면 그대로 반환
                        .toList();
            } catch (Exception e) {
                // 어떠한 예외라도 발생하게 되면 롤백 리스트에 있는 재고량 감소된 옵션을 다시 롤백(증가)
                rollbackList.forEach(it -> stockManageService.rollback(it.getId(), quantity).getOrThrow());
                throw e;
            }
        });
    }
```

2023-10-11 02:01 UTC, jinlee0 approved these changes

2023-10-11 02:02 UTC, merged