[관리자] 상품 추가
Liberty52/product pull request #300
Opened 2023-10-19 10:30 UTC by DryRains

## 스프린트 넘버  : 5
### 백로그 이름 : [관리자] 상품 추가

***
### 작업
상품 추가 기능 구현, 추가시 상품 사진도 함께 등록 가능하도록 구현
커스텀 상품인지, 라이선스 이미지 전용 상품인지 구분하는 필드 추가(isCustom)
**API**
```
PATCH admin/product/{productId}/introduction

>> REQUEST 
Headers: {
  LB-Role: role
}

image : {
  MultipartFile (required = false) //상품 사진
}

data (Content-type : application/json): { 
  "name" : String(Not Blank), //상품명
  "productState" : String(Not Null), //상품 상태(Enum : "ON_SALE" or "NOT_SALE")
  "price" : Long(Min:0), //상품 가격
  "isCustom" : Boolean(Not Null) //커스텀 상품인지(true), 라이선스 이미지 전용 상품인지(false)
}

>> RESPONSE
Status: 
  201: 생성 성공
  400: 잘못된 요청 데이터로 요청
  415: data 요청 Content-type을 application/json로 요청하지 않는 등 잘못된 요청 타입으로 요청시 발생하는 에러
<<
```

**CODE** 

***
### 테스트 결과
테스트 코드 해당 PR에서 작업후 추가 커밋으로 올리겠음

***

2023-10-19 10:54 UTC, ansm6358 approved these changes

2023-10-19 14:03 UTC, hseungho requested changes
좋습니다!

nit: 상품 추가에 따르는 응답값이 없는데, 개인적으로는 생성된 상품의 정보를 (일부) 반환하는 건 어떨까 싶어요. 그리고 테스트 코드도 보이지 않아서, 테스트코드 추가해주시면 좋을 것 같습니다!

2023-10-19 18:24 UTC, DryRains commented
> 좋습니다!
> 
> nit: 상품 추가에 따르는 응답값이 없는데, 개인적으로는 생성된 상품의 정보를 (일부) 반환하는 건 어떨까 싶어요. 그리고 테스트 코드도 보이지 않아서, 테스트코드 추가해주시면 좋을 것 같습니다!

테스트코드 추가하였고,
Controller단에서 Http 응답코드와 함께 ResponseDto 를 함께 반환하는 방식으로 수정했습니다! (코드 길이 최소화 위해 ModelMapper 의존성 추가)

2023-10-20 09:56 UTC, parkcoldroad approved these changes
lgtm 👍

2023-10-20 10:41 UTC, DryRains commented
> lgtm 👍
> Entity가 바뀐 부분은 erd에 반영해주세요!

넵~!!

2023-10-21 03:08 UTC, hseungho approved these changes

2023-10-21 03:42 UTC, merged